---
# Adds a set of test users to OpenShift
# ansible-playbook -i inventory/inventory.cfg -e password=something -e prefix=developer
- name: Add Users to OpenShift
  hosts: ocplab
  remote_user: ec2-user

  tasks:
    # htpasswd module requires passlib, just call httppasswd directlt
    - name: Add users
      command: "htpasswd -b {{htpasswd_path}} {{prefix}}{{item}} {{password}}"
      become: true
      with_sequence: start=0 end=50 format=%02d
