- name: Configure software on nodes
  become: yes
  remote_user: ec2-user
  hosts: masters
  vars:
    # Wetty
    system_user: "ec2-user"
    letsencrypt: false
    domain_name: "changeme!"
    workshop_password: "changeme!"
    openssl_self_signed:
      - name: '{{ domain_name }}'
        domains: ['*.{{ domain_name }}', '{{ domain_name }}']
        country: 'US'
        state: 'DC'
        city: 'Washington'
        organization: 'Example'
        unit: 'Business Unit'
        email: 'jsmith@example.com'
        days: 3650
    key_path:   "home/{{ system_user }}/.wetty/privkey.pem"
    cert_path:  "home/{{ system_user }}/.wetty/cert.pem"
    wetty_port:  8888
    wetty_user: "ec2-user" # "cockpit"
    # The namespace to which to add containerized Wetty components.
    component_namespace: wetty
    amazon_user: "ec2-user"
    #####################################################################
    # SSL configuration - Optional
    #####################################################################

    # Option 1: Install SSL certificates for the master that you provide or
    # were previously generated by Option 2
    # master_ssl_cert_file: "certs/letsencrypt/ocplab.com/fullchain.pem"
    # master_ssl_key_file: "certs/letsencrypt/ocplab.com/privkey.pem"
    # wildcard_ssl_fullchain_file: "certs/letsencrypt/apps.ocplab.com/fullchain.pem"
    # wildcard_ssl_cert_file: "certs/letsencrypt/apps.ocplab.com/fullchain.pem"
    # wildcard_ssl_key_file: "certs/letsencrypt/apps.ocplab.com/privkey.pem"

    # Option 2: Use let's encrypt to generate certs for master and hawkular
    # note certs will be fetched to location where script is run to back
    # them up and possible re-use
    use_lets_encrypt: true
    # e-mail address that owns the certs generated by letsencrypt
    domain_email_address: "me@me.com"
    # Generates a set of non-admin users that can be used for workshops,
    # demos, etc. Users are created with the prefix plus a number using
    # the password specified
    create_generic_user: true
    generic_user_prefix: "changeme!"
    generic_user_count: 30
    generic_user_password: "changeme!"
    generic_pass_prefix: "{{generic_user_password}}"
    generic_user_group: "oseuser"
    # Users
    openshift_cluster_admin_username: changeme!
    openshift_cluster_admin_password: changeme!
    openshift_test_users_prefix: user
    openshift_test_users_password: changeme!
    openshift_test_users_count: 20
    #####################################################################
    # Wetty - optional
    #####################################################################

    # Use wetty terminal over HTTP and HTTPS, which is an alternative to ajaxterm/anyterm
    # written entirely in Javascript
    install_wetty: false

    # OpenSSL self-signed certificate information for wetty terminal
    openssl_days: "365"
    openssl_country: "US"
    openssl_state: "California"
    openssl_city: "Los Angeles"
    openssl_organization: "Me, Inc."
    openssl_unit: "IT"
    # Minutes to pause between reboots
    reboot_wait_time: 1
  roles:
    - { role: wetty-install }
    # - { role: wetty }
    # - { role: wetty-deployer }
    # - { role: oc }
    # - { role: users }
